name = "handypad-landing"
compatibility_date = "2024-09-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "handypad"
database_id = "9ee6064a-001c-4c52-b27e-d24bc31b3df5"

[vars]
SITE_URL = "https://handypad.handyman.vn"
SALES_EMAIL = "sales@dlvcorp.com"
EMAIL_FROM = "marketing@samaser.com.vn"
BANK_BIN = "970432"
BANK_ACCOUNT = "54098995"
BANK_ACCOUNT_NAME = "DLV CORPORATION"
BANK_NAME = "VPBank - Chi nhanh Trung Son"
ODOO_URL = "https://dlvcorpodoo.odoo.com"
ODOO_DB = "samdo1980-dlvcorpodoo-main-36621845"
ODOO_USERNAME = "marketing@samaser.com.vn"
GOOGLE_SHEETS_WEBHOOK_URL = "https://script.google.com/macros/s/AKfycbz5lDlUERLZSDPZGwtXuaVaArhtMM2zhtrWNEvQspgw3wWgiYUnhxf3PQAJOuni6mgPPg/exec"``